// AUTO-GENERATED by scripts/gen_audio.py — do not edit
/* eslint-disable */

export const AUDIO = {
  chop: require('../../assets/audio/chop.mp3'),
  mine: require('../../assets/audio/mine.mp3'),
  hammer: require('../../assets/audio/hammer.mp3'),
  sword: require('../../assets/audio/sword.mp3'),
  arrow: require('../../assets/audio/arrow.mp3'),
  impact: require('../../assets/audio/impact.mp3'),
  bell: require('../../assets/audio/bell.mp3'),
  ageup: require('../../assets/audio/ageup.mp3'),
  built: require('../../assets/audio/built.mp3'),
  trained: require('../../assets/audio/trained.mp3'),
  alert: require('../../assets/audio/alert.mp3'),
  click: require('../../assets/audio/click.mp3'),
  select: require('../../assets/audio/select.mp3'),
  command: require('../../assets/audio/command.mp3'),
  death: require('../../assets/audio/death.mp3'),
  collapse: require('../../assets/audio/collapse.mp3'),
  coin: require('../../assets/audio/coin.mp3'),
  music_main: require('../../assets/audio/music_main.mp3'),
} as const;
export type SoundKey = Exclude<keyof typeof AUDIO, 'music_main'>;
